# -*- coding: utf-8 -*-
"""API_stock,fund,ETF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tCIpZhNIp7RK5SGybqg-TFE65UWtwbSa

## 📌 국내주식

### DART

- DART 활용 주의사항  
  1. Open DART 및 DART 홈페이지의 경우 분당 100회 이상 요청 시 서비스가 제한될 수 있음
  2. API KEY 외부 노출 금지
  3. 비상장/상장기업에 대한 정보 및 재무제표 정보 제공
"""

!pip install requests
!pip install dart-fss #dart 패키지 설치
!pip install opendartreader

import dart_fss as dart_fss
import pandas as pd

api_key = '240f822e52e7523dd65b33cc0903e8ec53f530f7'
dart_fss.set_api_key(api_key=api_key)


corp_list = dart_fss.get_corp_list()

corp_list.corps #기업 리스트 추출

"""### 한국거래소 PyKrx

- 참고사이트: https://github.com/sharebook-kr/pykrx
"""

!pip install pykrx

import pandas as pd
from pykrx import stock
from pykrx import bond
from time import sleep
import os
import time
from pykrx import stock
import pandas as pd
from datetime import datetime,timedelta

"""- PyKrx 종목을 설정하여 가장 최근 시세 조회하여 CSV 파일로 저장  
  - 현재 디렉토리 위치에 저장
"""

def get_recent_business_day():
    today = datetime.today()
    offset = 30  # 과거 30일 간 검색
    for i in range(offset):
        # 과거로 거슬러 올라가며 거래일 확인
        test_day = today - timedelta(days=i)
        formatted_day = test_day.strftime("%Y%m%d")
        # 해당 날짜에 주식 시장 데이터가 존재하는지 확인
        if not stock.get_market_ohlcv_by_date(formatted_day, formatted_day, "005930").empty:
            return formatted_day
    return None  # 30일 내에 거래일이 없으면 None 반환

def get_recent_stock_info(tickers):
    # 가장 최근의 거래일을 얻기
    recent_date = get_recent_business_day()
    if not recent_date:
        return pd.DataFrame()  # 최근 거래일을 찾지 못한 경우

    # 모든 주식 정보를 저장할 데이터프레임
    all_stocks = pd.DataFrame()

    # 주어진 모든 티커에 대해 정보를 수집
    for ticker in tickers:
        df = stock.get_market_ohlcv_by_date(recent_date, recent_date, ticker)
        if not df.empty:
            df['Ticker'] = ticker  # 종목코드 추가
            all_stocks = pd.concat([all_stocks, df])

    return all_stocks

# 종목 코드 리스트 (여기에 원하는 종목 코드 추가)
tickers = [
    "005930",  # 삼성전자
    "000660",  # SK하이닉스
    "035420",  # NAVER
    # 추가적인 종목 코드 입력...
]

# 주식 정보 조회
stock_info = get_recent_stock_info(tickers)

# CSV 파일로 저장
csv_file_path = "recent_stock_info.csv"
stock_info.to_csv(csv_file_path, index=True)
print(f"Saved to {csv_file_path}")

"""- 국내 주식 정보 및 종목코드 CSV 파일에 저장"""

from pykrx import stock
import pandas as pd

def get_stock_codes_and_names():
    # 모든 상장 주식의 코드와 이름을 DataFrame으로 가져오기
    df = stock.get_market_ticker_list(market="ALL", date=None)
    stock_info = pd.DataFrame({
        "Code": df,
        "Name": [stock.get_market_ticker_name(code) for code in df]
    })
    return stock_info

# 모든 주식 종목 코드와 이름 조회
all_stocks = get_stock_codes_and_names()

# CSV 파일로 저장
csv_file_path = "국내 주식 종목 코드.csv"
all_stocks.to_csv(csv_file_path, index=False)
print(f"Saved to {csv_file_path}")

"""## 📌 해외주식

### yfinance

- investpy 사용 막힘
"""

import investpy

def get_stock_info(stock_name, country):
    # 주식 정보 조회
    try:
        stock_info = investpy.get_stock_information(stock=stock_name, country=country)
        print(stock_info)
    except Exception as e:
        print(f"Error retrieving stock information: {e}")

    # 최근 주식 가격 데이터 조회
    try:
        recent_data = investpy.get_stock_recent_data(stock=stock_name, country=country)
        print(recent_data.tail())  # 최근 5일의 데이터 출력
    except Exception as e:
        print(f"Error retrieving recent stock data: {e}")

# 예시: 'Apple Inc' 주식의 정보와 최근 데이터를 미국에서 조회
get_stock_info('AAPL', 'united states')

!pip install yfinance

import yfinance as yf
import pandas as pd

def get_stocks_info(tickers):
    # 종목 정보를 저장할 데이터 프레임 생성
    stocks_info = pd.DataFrame()

    # 각 종목에 대한 정보 조회
    for ticker in tickers:
        stock = yf.Ticker(ticker)
        info = stock.info

        # 최근 종가 조회
        history = stock.history(period="1d")  # 가장 최근 거래일 데이터
        recent_close = history['Close'].iloc[-1] if not history.empty else None

        # 필요한 정보만 추출
        stock_data = {
            'Ticker': ticker,
            'Name': info.get('longName'),
            'Sector': info.get('sector'),
            'Industry': info.get('industry'),
            'Market Cap': info.get('marketCap'),
            'Price': recent_close,  # 최근 종가로 업데이트
            'Forward PE': info.get('forwardPE'),
            'Dividend Yield': info.get('dividendYield')  # 배당 수익률
        }
        # 데이터 프레임에 추가
        stock_data_df = pd.DataFrame([stock_data])
        stocks_info = pd.concat([stocks_info, stock_data_df], ignore_index=True)

    return stocks_info

def save_to_csv(tickers, filename='stocks_info.csv'):
    # 주식 정보 조회
    stocks_info_df = get_stocks_info(tickers)
    # CSV 파일로 저장
    stocks_info_df.to_csv(filename, index=False)
    print(f"Data saved to {filename}")

# 예시 종목 리스트
tickers = [
    "AAPL", "MSFT", "GOOGL", "AMZN", "FB", "TSLA", "NFLX",
    "INTC", "NVDA", "PYPL", "CSCO", "CMCSA", "PEP", "ADBE",
    "AMGN", "AVGO", "TXN", "COST", "QCOM", "V"
]

# 주식 정보를 CSV 파일로 저장
save_to_csv(tickers, '미국주식정보.csv')

"""## 📌 해외주식

ETF란 Exchange Traded Fund의 줄임말로 특정 지수를 추종하는 인덱스 펀드를 거래소에 상장시켜 주식처럼 거래할 수 있도록 만든 펀드를 뜻한다. 그래서 ETF는 '상장 지수 펀드'라고도 불린다.  

- ETF는 증권사 API를 활용하지 않고 네이버에서 크롤링 후 진행
- 출처: https://lazyquant.tistory.com/entry/백테스트-ETF-정보-조회네이버-금융-API-활용 [게으른 퀀트:티스토리]
- https://github.com/corazzon/finance-data-analysis/blob/main/4.1%20ETF%20%EB%AA%A9%EB%A1%9D%20%EC%88%98%EC%A7%91-output.ipynb
"""

import requests
import json
import pandas as pd

# 국내 ETF 전체 리스트를 가져오는 URL : naver finacne
url = 'https://finance.naver.com/api/sise/etfItemList.nhn'

# 요청을 보내고 응답을 받아 JSON으로 변환
response = requests.get(url)
json_data = json.loads(response.text)

# JSON 데이터에서 필요한 부분만 추출하여 DataFrame 생성
df_etf_list = pd.json_normalize(json_data['result']['etfItemList'])

# DataFrame을 CSV 파일로 저장
df_etf_list.to_csv('etf_list.csv', index=False, encoding='utf-8-sig')

print("etf_list.csv 파일 저장 완료")