# -*- coding: utf-8 -*-
"""Clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15FFr9Lpnf6ZjUJc18lQTwmKEWvsQJEIh

성향에 따른 분류
"""

import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.cluster import KMeans
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.decomposition import TruncatedSVD
import matplotlib.pyplot as plt
import numpy as np

# Load the generated data
file_path = '/content/drive/MyDrive/4-1 한이음/user.xlsx'
df = pd.read_excel(file_path)

# 아이디 칼럼 삭제
df_features = df.drop(columns=['아이디'])

# 투자성형 칼럼을 반복함으로써 가중치 부여
weighted_df_features = df_features.copy()
for i in range(4):  # 4번 반복
    weighted_df_features[f'투자성향_{i}'] = df_features['투자성향']

# 원-핫 인코딩 수행
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(), weighted_df_features.columns)
    ],
    remainder='passthrough'
)

# 파이프라인 구축
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('kmeans', KMeans(n_clusters=4, random_state=42))
])

# 파이프라인 학습
pipeline.fit(weighted_df_features)

# 클러스터 생성 후 칼럼 추가
df['Cluster'] = pipeline.predict(weighted_df_features)

svd = TruncatedSVD(n_components=2, random_state=42)
df_svd = svd.fit_transform(pipeline.named_steps['preprocessor'].transform(weighted_df_features))

# Create a scatter plot
plt.figure(figsize=(10, 7))
for cluster in range(4):
    plt.scatter(df_svd[df['Cluster'] == cluster][:, 0], df_svd[df['Cluster'] == cluster][:, 1], label=f'Cluster {cluster}')

plt.xlabel('SVD Component 1')
plt.ylabel('SVD Component 2')
plt.title('Clusters Visualization with Weighted Investment Tendency')
plt.legend()
plt.show()

# Get the cluster centers
cluster_centers_weighted = pipeline.named_steps['kmeans'].cluster_centers_

# Reverse the one-hot encoding to get the original feature values
encoder = pipeline.named_steps['preprocessor'].named_transformers_['cat']
feature_names = encoder.get_feature_names_out(weighted_df_features.columns)

# Decode the one-hot encoded features
decoded_centers_weighted = encoder.inverse_transform(cluster_centers_weighted)

# Create a DataFrame for decoded cluster centers
decoded_centers_df_weighted = pd.DataFrame(decoded_centers_weighted, columns=weighted_df_features.columns)

# Save the cluster centers to an Excel file for further analysis
output_file_path_weighted = '/content/drive/MyDrive/4-1 한이음/user_weighted.xlsx'
decoded_centers_df_weighted.to_excel(output_file_path_weighted, index=False)

# Display the cluster centers DataFrame
decoded_centers_df_weighted.head()

"""클러스터0 - 위험중립형 -> 일반적인 사람들 (상위 10개 기업)  
클러스터1 - 적극투자형 -> qld, 2배 etf (알아봐야함)  
클러스터2 - 공격투자형 -> 상승폭 상위랭킹 추천  
클러스터3 - 안정추구형 -> 지수추정 etf (분야가 딱히 나뉘어져있지 않음)

관심분야에 따른 추천
"""

import pandas as pd
import random
import yfinance as yf

# 관심분야 10개 목록 예시
interest_areas = [
    "Technology", "Healthcare", "Finance", "Energy", "Consumer Goods",
    "Utilities", "Real Estate", "Telecommunications", "Materials", "Industrials"
]

# 관심 분야에 따른 주요 주식 티커
stock_tickers = {
    "Technology": ["AAPL", "MSFT", "GOOGL", "AMZN", "META"],
    "Healthcare": ["JNJ", "PFE", "MRK", "ABBV", "TMO"],
    "Finance": ["JPM", "BAC", "C", "GS", "MS"],
    "Energy": ["XOM", "CVX", "COP", "SLB", "PSX"],
    "Consumer Goods": ["PG", "KO", "PEP", "PM", "MO"],
    "Utilities": ["NEE", "DUK", "SO", "D", "AEP"],
    "Real Estate": ["AMT", "PLD", "CCI", "EQIX", "PSA"],
    "Telecommunications": ["VZ", "T", "TMUS", "CHTR", "CMCSA"],
    "Materials": ["LIN", "APD", "ECL", "PPG", "SHW"],
    "Industrials": ["MMM", "HON", "BA", "RTX", "CAT"]
}

# 데이터프레임 생성
df_interest = pd.read_excel('/content/drive/MyDrive/4-1 한이음/user_interest.xlsx')

# 추천 주식 종목 추가 함수
def recommend_stocks(interest):
    tickers = stock_tickers.get(interest, [])
    recommendations = []
    for ticker in tickers:
        stock = yf.Ticker(ticker)
        info = stock.info
        recommendations.append(info['shortName'])
    return ", ".join(recommendations)

df_interest["추천 종목"] = df_interest["관심분야"].apply(recommend_stocks)

# 엑셀 파일로 저장
output_file_path = '/content/drive/MyDrive/4-1 한이음/user_interest_rec.xlsx'
df_interest.to_excel(output_file_path, index=False)

# Display the dataframe (replace with appropriate display code for your environment)
print(df_interest.head())

import pandas as pd
import yfinance as yf
from datetime import datetime, timedelta

# 관심 분야에 따른 주요 주식 티커
stock_tickers = {
    "Technology": ["AAPL", "MSFT", "GOOGL", "AMZN", "META", "ORCL", "INTC", "CSCO", "ADBE", "NVDA"],
    "Healthcare": ["JNJ", "PFE", "MRK", "ABBV", "TMO", "UNH", "BMY", "GILD", "LLY", "AMGN"],
    "Finance": ["JPM", "BAC", "C", "GS", "MS", "WFC", "BLK", "SCHW", "AXP", "BK"],
    "Energy": ["XOM", "CVX", "COP", "SLB", "PSX", "EOG", "KMI", "MPC", "HAL", "VLO"],
    "Consumer Goods": ["PG", "KO", "PEP", "PM", "MO", "UL", "CL", "NKE", "MDLZ", "KMB"],
    "Utilities": ["NEE", "DUK", "SO", "D", "AEP", "EXC", "SRE", "PEG", "ED", "XEL"],
    "Real Estate": ["AMT", "PLD", "CCI", "EQIX", "PSA", "SPG", "DLR", "O", "WELL", "VTR"],
    "Telecommunications": ["VZ", "T", "TMUS", "CHTR", "CMCSA", "DISH", "VOD", "NTES", "BIDU", "CHL"],
    "Materials": ["LIN", "APD", "ECL", "PPG", "SHW", "NEM", "FCX", "CTVA", "DOW", "DD"],
    "Industrials": ["MMM", "HON", "BA", "RTX", "CAT", "LMT", "GE", "UPS", "FDX", "DE"]
}

# 엑셀 파일 불러오기
input_file_path = '/mnt/data/generated_data_1000.xlsx'
df = pd.read_excel(input_file_path)

# 클러스터 2에 속하는 사용자 필터링
cluster_2_users = df[df['Cluster'] == 2]

# 주식 상승률 계산 및 추천 함수
def calculate_stock_performance(ticker):
    stock = yf.Ticker(ticker)
    end_date = datetime.now()
    start_date = end_date - timedelta(days=365)
    hist = stock.history(start=start_date, end=end_date)
    if len(hist) < 2:
        return 0  # 데이터가 충분하지 않으면 상승률 0으로 처리
    return (hist['Close'][-1] - hist['Close'][0]) / hist['Close'][0]

def recommend_stocks(interest):
    tickers = stock_tickers.get(interest, [])
    performances = []
    for ticker in tickers:
        try:
            performance = calculate_stock_performance(ticker)
            performances.append((ticker, performance))
        except Exception as e:
            continue  # 오류가 발생하면 해당 주식 무시
    performances.sort(key=lambda x: x[1], reverse=True)
    top_3 = [ticker for ticker, _ in performances[:3]]
    return ", ".join(top_3)

# 클러스터 2 사용자에 대한 주식 추천 생성
cluster_2_users['추천 종목'] = cluster_2_users['관심분야'].apply(recommend_stocks)

# 결과를 엑셀 파일로 저장
output_file_path_with_recommendations = '/mnt/data/cluster_2_stock_recommendations.xlsx'
cluster_2_users.to_excel(output_file_path_with_recommendations, index=False)

# Display the dataframe
cluster_2_users.head()

pip install yfinance

import yfinance as yf

# 기본적으로 사용할 주식 티커 목록 (이 목록은 확장 가능)
tickers_list = ['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'TSLA', 'JPM', 'GS', 'C', 'BAC', 'AXP', 'MRNA', 'TMO', 'VRTX', 'REGN', 'ILMN']

def get_industry_list(tickers):
    industries = set()
    for ticker in tickers:
        stock = yf.Ticker(ticker)
        stock_info = stock.info
        if 'industry' in stock_info:
            industries.add(stock_info['industry'])
    return list(industries)

# 사용 예시
industries = get_industry_list(tickers_list)
print("관심 분야(interest) 리스트:")
for industry in industries:
    print(industry)

a={'일본','중국','한국'}
a.add('베트남')
a.add('중국')
a.remove('일본')
a.update(['홍콩','한국','태국'])
print(a)

