# -*- coding: utf-8 -*-
"""Crawling_news_YSKim

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/102l_rR6ZGBGmGeW6epai9PQ5QVhcUsY5

## 크롤링
"""

pip install requests

# 네이버 경제 뉴스 기사 크롤링
# 2024.05.06 YSKim
# title(기사제목), link(링크), content(기사본문)

import requests
from bs4 import BeautifulSoup

# 네이버 금융 뉴스 URL
url = "https://news.naver.com/main/list.naver?mode=LSD&mid=sec&sid1=101"

# HTTP GET 요청
response = requests.get(url)
response.encoding = 'euc-kr'  # 네이버 뉴스 페이지의 인코딩 방식에 맞춰 인코딩 설정

# BeautifulSoup 객체 생성
soup = BeautifulSoup(response.text, 'html.parser')

# 뉴스 기사 제목과 링크 추출
news_list = soup.select('.newsflash_body .type06_headline li dl')
news_data = []
for news in news_list:
    title = news.find("dt", {"class": ""}).text.replace('\t', '').replace('\n', '').replace('\r', '').strip()
    link = news.find("a")["href"]
    # HTTP GET 요청으로 개별 뉴스 페이지 접근
    news_response = requests.get(link)
    news_response.encoding = 'utf-8-sig'
    news_soup = BeautifulSoup(news_response.text, 'html.parser')
    # 뉴스 본문 추출
    content_area = news_soup.select_one('.go_trans._article_content')
    if content_area:
        content = content_area.text.replace('\n', '').replace('\t', '').replace('\r', '').strip()
    else:
        content = "본문을 불러올 수 없습니다."
    news_data.append({"title": title, "link": link, "content": content})

# 추출된 뉴스 기사 제목, 링크 및 본문 출력
for news in news_data:
    print(news['title'])
    print(news['link'])
    print(news['content'])
    print()

# 인덱스 포함

import requests
from bs4 import BeautifulSoup

# 네이버 금융 뉴스 URL
url = "https://news.naver.com/main/list.naver?mode=LSD&mid=sec&sid1=101"

# HTTP GET 요청
response = requests.get(url)
response.encoding = 'euc-kr'  # 네이버 뉴스 페이지의 인코딩 방식에 맞춰 인코딩 설정

# BeautifulSoup 객체 생성
soup = BeautifulSoup(response.text, 'html.parser')

# 뉴스 기사 제목과 링크 추출
news_list = soup.select('.newsflash_body .type06_headline li dl')
news_data = []
for news in news_list:
    title = news.find("dt", {"class": ""}).text.replace('\t', '').replace('\n', '').replace('\r', '').strip()
    link = news.find("a")["href"]
    # HTTP GET 요청으로 개별 뉴스 페이지 접근
    news_response = requests.get(link)
    news_response.encoding = 'utf-8-sig'
    news_soup = BeautifulSoup(news_response.text, 'html.parser')
    # 뉴스 본문 추출
    content_area = news_soup.select_one('.go_trans._article_content')
    if content_area:
        content = content_area.text.replace('\n', '').replace('\t', '').replace('\r', '').strip()
    else:
        content = "본문을 불러올 수 없습니다."
    news_data.append({"title": title, "link": link, "content": content})

# 추출된 뉴스 기사 제목, 링크 및 본문을 인덱스와 함께 출력
for index, news in enumerate(news_data, start=1):
    print(f"뉴스 인덱스: {index}")
    print(f"제목: {news['title']}")
    print(f"링크: {news['link']}")
    print(f"본문: {news['content']}")
    print("\n")

"""## 최종 크롤링 코드 (DataFrame)"""

# 기사별 dataframe 형태로 출력
# Title, Link, Content

import requests
from bs4 import BeautifulSoup
import pandas as pd

# 네이버 금융 뉴스 URL
url = "https://news.naver.com/main/list.naver?mode=LSD&mid=sec&sid1=101"

# HTTP GET 요청
response = requests.get(url)
response.encoding = 'euc-kr'  # 네이버 뉴스 페이지의 인코딩 방식에 맞춰 인코딩 설정

# BeautifulSoup 객체 생성
soup = BeautifulSoup(response.text, 'html.parser')

# 뉴스 기사 제목과 링크 추출
news_list = soup.select('.newsflash_body .type06_headline li dl')
news_data = []
for index, news in enumerate(news_list, start=1):
    title = news.find("dt", {"class": ""}).text.replace('\t', '').replace('\n', '').replace('\r', '').strip()
    link = news.find("a")["href"]
    # HTTP GET 요청으로 개별 뉴스 페이지 접근
    news_response = requests.get(link)
    news_response.encoding = 'utf-8-sig'
    news_soup = BeautifulSoup(news_response.text, 'html.parser')
    # 뉴스 본문 추출
    content_area = news_soup.select_one('.go_trans._article_content')
    if content_area:
        content = content_area.text.replace('\n', '').replace('\t', '').replace('\r', '').strip()
    else:
        content = "본문을 불러올 수 없습니다."

    # 인덱스를 포함한 기사 정보를 리스트에 추가
    news_data.append({"Index": index, "Title": title, "Link": link, "Content": content})

# 데이터 프레임 생성
df = pd.DataFrame(news_data)

# 데이터 프레임 출력
print(df)

df.shape

# Content(기사본문)만 출력

df["Content"]

df["Content"].shape

