# -*- coding: utf-8 -*-
"""LSTM_성능개선과정.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aFzOkQBygsHfzQqKVTZS7hxXMm1BgocL
"""

pip install pandas numpy yfinance tensorflow scikit-learn

import yfinance as yf
import pandas as pd
from sklearn.model_selection import train_test_split

# 기업 리스트
companies = {
    "META": "Meta Platforms, Inc.",
    "JNJ": "Johnson & Johnson",
    "PFE": "Pfizer Inc.",
    "WMT": "Walmart Inc.",
}

# 주가 데이터 수집
def get_stock_data(ticker):
    data = yf.download(ticker, start="2023-01-01", end="2024-07-31")
    return data

# 모든 기업의 데이터를 저장
stock_data = {ticker: get_stock_data(ticker) for ticker in companies.keys()}

import numpy as np

# 감성 분석 점수 생성 (0: 부정, 1: 긍정)
def generate_sentiment_scores(data):
    return np.random.choice([0, 1], size=len(data)) # 지금은 random으로 설정

# 각 기업의 감성 점수 추가
for ticker, data in stock_data.items():
    data['Sentiment'] = generate_sentiment_scores(data)

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from sklearn.preprocessing import MinMaxScaler

# LSTM 모델을 위한 데이터 전처리
def prepare_data(data, n_steps=60):
    scaler = MinMaxScaler(feature_range=(0, 1))
    scaled_data = scaler.fit_transform(data[['Close']])

    X, y = [], []
    for i in range(n_steps, len(scaled_data)):
        X.append(scaled_data[i-n_steps:i, 0])
        y.append(scaled_data[i, 0])

    X = np.array(X)
    y = np.array(y)

    return X.reshape((X.shape[0], X.shape[1], 1)), y, scaler

# LSTM 모델 생성
def create_lstm_model(input_shape):
    model = Sequential()
    model.add(LSTM(units=50, return_sequences=True, input_shape=input_shape))
    model.add(Dropout(0.2))
    model.add(LSTM(units=50, return_sequences=False))
    model.add(Dropout(0.2))
    model.add(Dense(units=1))
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

# 모델 훈련 및 예측
def train_and_predict(data, n_steps=60):
    X, y, scaler = prepare_data(data, n_steps)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

    model = create_lstm_model((X_train.shape[1], 1))
    model.fit(X_train, y_train, epochs=10, batch_size=32)

    predicted_prices = model.predict(X_test)
    predicted_prices = scaler.inverse_transform(predicted_prices)

    return predicted_prices, scaler.inverse_transform(y_test.reshape(-1, 1))

# 각 기업에 대해 모델 훈련 및 예측
predictions = {}
for ticker, data in stock_data.items():
    predicted, actual = train_and_predict(data)
    predictions[ticker] = (predicted, actual)

import matplotlib.pyplot as plt
import pandas as pd

def plot_predictions(ticker, dates, predicted, actual):
    plt.figure(figsize=(12,6))
    plt.plot(dates, actual, color='red', label='Actual Price')
    plt.plot(dates, predicted, color='blue', label='Predicted Price')
    plt.title(f'{companies[ticker]} Stock Price Prediction')
    plt.xlabel('Date')
    plt.ylabel('Price')
    plt.xticks(rotation=45)
    plt.legend()
    plt.grid(True)
    plt.show()

# 각 기업의 예측 결과 시각화
# 예측 및 실제 데이터에 해당하는 날짜 생성 또는 제공된 데이터 사용
for ticker, (predicted, actual) in predictions.items():
    # 예시로 날짜 생성 (실제 데이터에 맞게 조정 필요)
    dates = pd.date_range(start='2024-06-01', periods=len(actual), freq='D')
    plot_predictions(ticker, dates, predicted, actual)

import yfinance as yf
import matplotlib.pyplot as plt

# 기업 리스트
companies = {
    "META": "Meta Platforms, Inc.",
    "JNJ": "Johnson & Johnson",
    "PFE": "Pfizer Inc.",
    "WMT": "Walmart Inc.",
}

# 주가 데이터 수집
def get_stock_data(ticker):
    data = yf.download(ticker, start="2023-01-01", end="2024-08-31")
    return data

# 모든 기업의 데이터를 저장
stock_data = {ticker: get_stock_data(ticker) for ticker in companies.keys()}


# 주가 데이터 시각화
def plot_stock_data(ticker, data):
    plt.figure(figsize=(12, 6))
    plt.plot(data.index, data['Close'], label=f"{companies[ticker]} Closing Price")
    plt.title(f'{companies[ticker]} Stock Price (2023-2024)')
    plt.xlabel('Date')
    plt.ylabel('Price (USD)')
    plt.xticks(rotation=45)
    plt.legend()
    plt.grid(True)
    plt.show()

# 각 기업의 주가 시각화
for ticker, data in stock_data.items():
    plot_stock_data(ticker, data)

import yfinance as yf
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

# 기업 리스트
companies = {
    "META": "Meta Platforms, Inc.",
    "JNJ": "Johnson & Johnson",
    "PFE": "Pfizer Inc.",
    "WMT": "Walmart Inc.",
}

# 주가 데이터 수집
def get_stock_data(ticker):
    data = yf.download(ticker, start="2023-01-01", end="2024-08-31")
    return data

# 모든 기업의 데이터를 저장
stock_data = {ticker: get_stock_data(ticker) for ticker in companies.keys()}

# LSTM 모델을 위한 데이터 전처리 및 예측
def prepare_data(data, n_steps=60):
    scaler = MinMaxScaler(feature_range=(0, 1))
    scaled_data = scaler.fit_transform(data[['Close']])

    X, y = [], []
    for i in range(n_steps, len(scaled_data)):
        X.append(scaled_data[i-n_steps:i, 0])
        y.append(scaled_data[i, 0])

    X = np.array(X)
    y = np.array(y)

    return X.reshape((X.shape[0], X.shape[1], 1)), y, scaler

# LSTM 모델 생성
def create_lstm_model(input_shape):
    model = Sequential()
    model.add(LSTM(units=50, return_sequences=True, input_shape=input_shape))
    model.add(Dropout(0.2))
    model.add(LSTM(units=50, return_sequences=False))
    model.add(Dropout(0.2))
    model.add(Dense(units=1))
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

# 모델 훈련 및 예측
def train_and_predict(data, n_steps=60):
    X, y, scaler = prepare_data(data, n_steps)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

    model = create_lstm_model((X_train.shape[1], 1))
    model.fit(X_train, y_train, epochs=10, batch_size=32)

    predicted_prices = model.predict(X_test)
    predicted_prices = scaler.inverse_transform(predicted_prices)

    return predicted_prices, scaler.inverse_transform(y_test.reshape(-1, 1))

# 시각화 함수
def plot_stock_data_with_prediction(ticker, data, predicted, actual):
    plt.figure(figsize=(12, 6))
    plt.plot(data.index[-len(actual):], actual, color='red', label='Actual Price')
    plt.plot(data.index[-len(predicted):], predicted, color='blue', label='Predicted Price')
    plt.plot(data.index, data['Close'], label=f"{companies[ticker]} Closing Price", alpha=0.3)
    plt.title(f'{companies[ticker]} Stock Price Prediction')
    plt.xlabel('Date')
    plt.ylabel('Price (USD)')
    plt.xticks(rotation=45)
    plt.legend()
    plt.grid(True)
    plt.show()

# 각 기업에 대해 모델 훈련 및 예측
predictions = {}
for ticker, data in stock_data.items():
    predicted, actual = train_and_predict(data)
    predictions[ticker] = (predicted, actual)

# 예측 결과 시각화
for ticker, (predicted, actual) in predictions.items():
    plot_stock_data_with_prediction(ticker, stock_data[ticker], predicted, actual)

# 추천 여부 판단 함수
def recommend_stock(predicted, actual, period=5):
    # 마지막 period 기간 동안의 평균 주가 변화 계산
    pred_diff = np.mean(predicted[-period:]) - np.mean(predicted[-(period*2):-period])
    actual_diff = np.mean(actual[-period:]) - np.mean(actual[-(period*2):-period])

    # 실제 주가와 예측 주가가 둘 다 상승세를 보이는지 확인
    if pred_diff > 0 and actual_diff > 0:
        print("추천: 최근 상승세를 보이고 있습니다.")
    else:
        print("비추천: 최근 상승세가 아닙니다.")

# 각 기업에 대해 모델 훈련 및 예측
predictions = {}
for ticker, data in stock_data.items():
    predicted, actual = train_and_predict(data)
    predictions[ticker] = (predicted, actual)
    print(f"{companies[ticker]} ({ticker}):")
    recommend_stock(predicted, actual)

# 예측 결과 시각화
for ticker, (predicted, actual) in predictions.items():
    plot_stock_data_with_prediction(ticker, stock_data[ticker], predicted, actual)

# 시각화 함수 (예측 기간만 표시)
def plot_prediction_only(ticker, data, predicted, actual):
    prediction_length = len(predicted)

    # 예측 구간의 실제 가격과 예측 가격만 표시
    plt.figure(figsize=(12, 6))
    plt.plot(data.index[-prediction_length:], actual, color='red', label='Actual Price')
    plt.plot(data.index[-prediction_length:], predicted, color='blue', label='Predicted Price')

    plt.title(f'{companies[ticker]} Stock Price Prediction (Prediction Period)')
    plt.xlabel('Date')
    plt.ylabel('Price (USD)')
    plt.xticks(rotation=45)
    plt.legend()
    plt.grid(True)
    plt.show()

# 각 기업의 예측 구간에 대한 그래프 출력
for ticker, (predicted, actual) in predictions.items():
    plot_prediction_only(ticker, stock_data[ticker], predicted, actual)

