# -*- coding: utf-8 -*-
"""LSTM_YSKim.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jlWsUe0sfDNC3e0fvqyO04hhTK0mUY7M
"""

# 필요한 라이브러리 설치
!pip install pykrx
from pykrx import stock
import pandas as pd
import numpy as np

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

# 특정 기간 동안의 삼성전자(005930) 주식 데이터 가져오기
df = stock.get_market_ohlcv_by_date("20240201", "20240517", "005930") # ("시작일", "종료일", "주식종목")

# 데이터 출력
print(df)

# 시가 예측 모델이므로 시가 제외 데이터 준비
stock_df = df.loc[:,['고가','저가','종가','거래량']]

# 시가 데이터 저장
original_open = df['시가'].values

# 날짜 데이터 저장
dates = df.index

# 학습데이터 변수
cols = list(stock_df)[1:6]

# 새로운 데이터 프레임(training data)
stock_data = stock_df[cols].astype(float)

# LSTM 활성화함수가 tanh와 sigmoid이므로 학습용 데이터 정규화
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler = scaler.fit(stock_df)
stock_data_scaled = scaler.transform(stock_df)

# train data와 test data 분리
n_train = int(0.9*stock_data_scaled.shape[0])
train_data_scaled = stock_data_scaled[0: n_train]
train_dates = dates[0: n_train]

test_data_scaled = stock_data_scaled[n_train:]
test_dates = dates[n_train:]

# data reformatting for LSTM
pred_days = 1  # prediction period
seq_len = 5   # sequence length = past days for future prediction.
input_dim = 5  # input_dimension = ['Open', 'High', 'Low', 'Close', 'Volume']

trainX = []
trainY = []
testX = []
testY = []

for i in range(seq_len, n_train-pred_days +1):
    trainX.append(train_data_scaled[i - seq_len:i, 0:train_data_scaled.shape[1]])
    trainY.append(train_data_scaled[i + pred_days - 1:i + pred_days, 0])

for i in range(seq_len, len(test_data_scaled)-pred_days +1):
    testX.append(test_data_scaled[i - seq_len:i, 0:test_data_scaled.shape[1]])
    testY.append(test_data_scaled[i + pred_days - 1:i + pred_days, 0])

trainX, trainY = np.array(trainX), np.array(trainY)
testX, testY = np.array(testX), np.array(testY)

# LSTM 모델 구성
model = Sequential()
model.add(LSTM(64, input_shape=(trainX.shape[1], trainX.shape[2]), return_sequences=True))
model.add(Dense(trainY.shape[1]))

# 모델 컴파일
model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])

history = model.fit(trainX, trainY, epochs=10, batch_size=32, validation_split=0.2, verbose=1)

# 모델 평가
test_loss, test_mae = model.evaluate(testX, testY, verbose=0)
print(f'Test Loss: {test_loss}, Test MAE: {test_mae}')

import matplotlib.pyplot as plt

plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Model Loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend()
plt.show()

