# -*- coding: utf-8 -*-
"""LSTM_hanium.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TXbTokH5ET2DMWWmQg-FZW6lnq6Rpi3J
"""

pip install pandas numpy yfinance tensorflow scikit-learn

import yfinance as yf
import pandas as pd
from sklearn.model_selection import train_test_split

# 기업 리스트
companies = {
    "AAPL": "Apple Inc.",
    "MSFT": "Microsoft Corporation",
    "GOOGL": "Alphabet Inc.",
    "AMZN": "Amazon.com, Inc.",
    "NVDA": "NVIDIA Corporation",
    "TSLA": "Tesla, Inc.",
    "META": "Meta Platforms, Inc.",
    "JNJ": "Johnson & Johnson",
    "PFE": "Pfizer Inc.",
    "MRK": "Merck & Co., Inc.",
    "UNH": "UnitedHealth Group Incorporated",
    "ABT": "Abbott Laboratories",
    "BMY": "Bristol-Myers Squibb Company",
    "LLY": "Eli Lilly and Company"
}

# 주가 데이터 수집
def get_stock_data(ticker):
    data = yf.download(ticker, start="2023-01-01", end="2024-07-31")
    return data

# 모든 기업의 데이터를 저장
stock_data = {ticker: get_stock_data(ticker) for ticker in companies.keys()}

import numpy as np

# 가상의 감성 분석 점수 생성 (0: 부정, 1: 긍정)
def generate_sentiment_scores(data):
    return np.random.choice([0, 1], size=len(data))

# 각 기업의 감성 점수 추가
for ticker, data in stock_data.items():
    data['Sentiment'] = generate_sentiment_scores(data)

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from sklearn.preprocessing import MinMaxScaler

# LSTM 모델을 위한 데이터 전처리
def prepare_data(data, n_steps=60):
    scaler = MinMaxScaler(feature_range=(0, 1))
    scaled_data = scaler.fit_transform(data[['Close']])

    X, y = [], []
    for i in range(n_steps, len(scaled_data)):
        X.append(scaled_data[i-n_steps:i, 0])
        y.append(scaled_data[i, 0])

    X = np.array(X)
    y = np.array(y)

    return X.reshape((X.shape[0], X.shape[1], 1)), y, scaler

# LSTM 모델 생성
def create_lstm_model(input_shape):
    model = Sequential()
    model.add(LSTM(units=50, return_sequences=True, input_shape=input_shape))
    model.add(Dropout(0.2))
    model.add(LSTM(units=50, return_sequences=False))
    model.add(Dropout(0.2))
    model.add(Dense(units=1))
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

# 모델 훈련 및 예측
def train_and_predict(data, n_steps=60):
    X, y, scaler = prepare_data(data, n_steps)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

    model = create_lstm_model((X_train.shape[1], 1))
    model.fit(X_train, y_train, epochs=10, batch_size=32)

    predicted_prices = model.predict(X_test)
    predicted_prices = scaler.inverse_transform(predicted_prices)

    return predicted_prices, scaler.inverse_transform(y_test.reshape(-1, 1))

# 각 기업에 대해 모델 훈련 및 예측
predictions = {}
for ticker, data in stock_data.items():
    predicted, actual = train_and_predict(data)
    predictions[ticker] = (predicted, actual)

import matplotlib.pyplot as plt

def plot_predictions(ticker, predicted, actual):
    plt.figure(figsize=(12,6))
    plt.plot(actual, color='red', label='Actual Price')
    plt.plot(predicted, color='blue', label='Predicted Price')
    plt.title(f'{companies[ticker]} Stock Price Prediction')
    plt.xlabel('Time')
    plt.ylabel('Price')
    plt.legend()
    plt.show()

# 각 기업의 예측 결과 시각화
for ticker, (predicted, actual) in predictions.items():
    plot_predictions(ticker, predicted, actual)

investment_decision = {ticker: "Invest" if (predicted[-1] - actual[-1]) > 0 else "Do not invest" for ticker, (predicted, actual) in predictions.items()}

# Apple 주식 데이터 수집
apple_data = get_stock_data("AAPL")

# 감성 분석 점수 추가 (가상 데이터로 대체)
apple_data['Sentiment'] = generate_sentiment_scores(apple_data)

# LSTM 모델을 위한 데이터 준비 및 예측
predicted_prices, actual_prices = train_and_predict(apple_data)

# 예측된 가격과 실제 가격 출력 (마지막 10일)
print(f"Actual prices (last 10 days): {actual_prices[-10:].flatten()}")
print(f"Predicted prices (last 10 days): {predicted_prices[-10:].flatten()}")

# 마지막 예측된 가격과 실제 가격을 비교하여 투자 결정을 내림
investment_decision = "Invest" if (predicted_prices[-1] - actual_prices[-1]) > 0 else "Do not invest"

print(f"Investment decision for Apple (AAPL): {investment_decision}")

import matplotlib.pyplot as plt
import pandas as pd

def plot_predictions(ticker, dates, predicted, actual):
    plt.figure(figsize=(12,6))
    plt.plot(dates, actual, color='red', label='Actual Price', marker='o')
    plt.plot(dates, predicted, color='blue', label='Predicted Price', marker='o')
    plt.title(f'{companies[ticker]} Stock Price Prediction')
    plt.xlabel('Date')
    plt.ylabel('Price')
    plt.xticks(rotation=45)
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.show()

# 각 기업의 예측 결과 시각화
# 예측 및 실제 데이터에 해당하는 날짜 생성 또는 제공된 데이터 사용
for ticker, (predicted, actual) in predictions.items():
    # 예시로 날짜 생성 (실제 데이터에 맞게 조정 필요)
    dates = pd.date_range(start='2023-01-01', periods=len(actual), freq='D')
    plot_predictions(ticker, dates, predicted, actual)

import yfinance as yf
import matplotlib.pyplot as plt

def plot_predictions(ticker, dates, predicted, actual):
    plt.figure(figsize=(12,6))
    plt.plot(dates, actual, color='red', label='Actual Price', marker='o')
    plt.plot(dates, predicted, color='blue', label='Predicted Price', marker='o')
    plt.title(f'{companies[ticker]} Stock Price Prediction')
    plt.xlabel('Date')
    plt.ylabel('Price')
    plt.xticks(rotation=45)
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.show()

# 각 기업의 예측 결과 시각화
for ticker, (predicted, actual) in predictions.items():
    # 실제 주가 데이터를 yfinance에서 가져오기
    stock_data = yf.download(ticker, start="2023-01-01", end="2024-07-31")

    # 주가 데이터에서 'Date'와 'Close' 열 가져오기
    dates = stock_data.index[-len(actual):]  # 실제 데이터 길이에 맞추기
    actual_prices = stock_data['Close'][-len(actual):]

    # 예측 데이터가 실제 데이터와 같은 길이로 잘려있다고 가정
    plot_predictions(ticker, dates, predicted, actual)

import yfinance as yf
import matplotlib.pyplot as plt
import numpy as np

def plot_predictions(ticker, dates, predicted, actual, future_dates=None, future_predictions=None):
    plt.figure(figsize=(12,6))
    plt.plot(dates, actual, color='red', label='Actual Price', marker='o')
    plt.plot(dates, predicted, color='blue', label='Predicted Price', marker='o')

    if future_dates is not None and future_predictions is not None:
        plt.plot(future_dates, future_predictions, color='green', label='Future Predictions', marker='x')

    plt.title(f'{companies[ticker]} Stock Price Prediction')
    plt.xlabel('Date')
    plt.ylabel('Price')
    plt.xticks(rotation=45)
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.show()

# 각 기업의 예측 결과 시각화 및 미래 예측
for ticker, (predicted, actual) in predictions.items():
    # 실제 주가 데이터를 yfinance에서 가져오기
    stock_data = yf.download(ticker, start="2023-01-01", end="2024-07-31")

    # 주가 데이터에서 'Date'와 'Close' 열 가져오기
    dates = stock_data.index[-len(actual):]  # 실제 데이터 길이에 맞추기
    actual_prices = stock_data['Close'][-len(actual):]

    # 미래 예측을 위한 기간 설정 (예: 30일)
    future_periods = 30
    last_date = stock_data.index[-1]
    future_dates = pd.date_range(start=last_date, periods=future_periods + 1, freq='D')[1:]

    # 간단한 미래 예측 (예: 이전 예측 값의 마지막 값 사용)
    # 실제로는 모델을 사용해 미래 예측 값을 생성해야 함
    future_predictions = np.full(future_periods, predicted[-1])  # 예를 들어 마지막 예측 값을 계속 사용

    # 미래 예측 값과 함께 플롯 생성
    plot_predictions(ticker, dates, predicted, actual, future_dates, future_predictions)

